name: Windows Runner Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: windows-runner-d

    steps:
      - uses: actions/checkout@v4

      - name: Show Runner Details
        shell: powershell
        run: |
          hostname
          whoami
          Get-Date
          echo "Running from D Drive"
          dir D:\
